### ISSUE TITLE
Broken Music Thread

### ISSUE THREAD

**Issue by OtacilioN** [ThiagoAugustoSM/arduino-tablature#5]
Some music isn't working? No problem, report here and the community will work to fix it.

Please, help with the steps to reproduce, follow this example:

- The music: https://www.cifraclub.com.br/hinos/hino-nacional-brasileiro/
- The error:
````requesting from:https://www.cifraclub.com.br/hinos/hino-nacional-brasileiro/
/home/ubuntu/workspace/arduino-tablature/index.js:321
        if(tabs[i][j][k] != "PAUSE"){
                     ^

TypeError: Cannot read property '0' of undefined
    at generateFile (/home/ubuntu/workspace/arduino-tablature/index.js:321:22)
    at Request._callback (/home/ubuntu/workspace/arduino-tablature/index.js:40:23)
    at Request.self.callback (/home/ubuntu/workspace/arduino-tablature/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/ubuntu/workspace/arduino-tablature/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/ubuntu/workspace/arduino-tablature/node_modules/request/request.js:1085:12)
````
- A Screenshot:

![image](https://user-images.githubusercontent.com/10578275/36356558-8e5ef2c2-14d2-11e8-8b8c-c0c2f07d7f86.png)

**Comment by clovisf** [comment]
Testadas e não funcionando (geralmente o erro é que aparece "undefined" ao invés da nota no campo 'tone'. Exemplo:  tone(buzzerPin, undefined);

https://www.cifraclub.com.br/ana-vilela/trem-bala/
https://www.cifraclub.com.br/hinos/hino-nacional-brasileiro/
https://www.cifraclub.com.br/ed-sheeran/perfect/
https://www.cifraclub.com.br/thiago-brava/dona-maria-part-jorge/

Pra falar a verdade ainda não testei uma música que compilasse na IDE do Arduino. Todas as música acima são baixadas pelo node, porém não compilam na IDE (V 1.8.5)

**Comment by OtacilioN** [comment]
Working right now to fix it @clovisf, we will tag you here when it get fixed!

**Comment by OtacilioN** [comment]
@clovisf  

https://www.cifraclub.com.br/thiago-brava/dona-maria-part-jorge/ fixed in [this commit ](https://github.com/ThiagoAugustoSM/arduino-tablature/commit/3ea420541c7177c5e8f3bfbdf4df096ca932ee29), by updating your clone it will be fixed.
